packages:
  - packages/provider
  - packages/railgun
  - packages/privacy-pools
  - packages/plugins
  - packages/railgun-plugin
  - packages/tc-plugin
  - docs

onlyBuiltDependencies:
  - blake-hash
  - keccak
