packages:
  - packages/provider
  - packages/railgun
  - packages/privacy-pools
  - packages/plugins
  - packages/tornado-cash
  - examples/pq-account
  - docs

autoInstallPeers: false

onlyBuiltDependencies:
  - blake-hash
  - esbuild
patchedDependencies:
  snarkjs@0.1.20: patches/snarkjs@0.1.20.patch
