allowBuilds:
  blake-hash: true
  es5-ext: true
  esbuild: true
  keccak: true
  msgpackr-extract: true
  protobufjs: true
autoInstallPeers: false
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@privacy-paymasters/sdk@0.0.4'
packages:
  - "packages/provider"
  - "packages/privacy-pools"
  - "packages/plugins"
  - "packages/tornado-cash"
  - "packages/mimc-tree"
  - "examples/pq-account"
  - "crates/railgun-ts"
  - "docs"
